### ISSUE TITLE
CI/CD 빈스톡 연결

### ISSUE THREAD

**Issue by kkyu0718** [cmc-say-server/server#1]
- 빈스톡 세팅
- ci/cd 스크립트 작성

**Comment by stopkite** [comment]
와 멋져요 >< !! say 팀 파이팅!!!!!!!!!!

**Comment by kkyu0718** [comment]
> 와 멋져요 >< !! say 팀 파이팅!!!!!!!!!!
![image](https://user-images.githubusercontent.com/80209277/218276476-38dc157e-20b9-42fe-a1ac-fe3756b98623.png)
14분 째 이러는 친구 정상일까요?
살려줘요 (당근) (당근)
